### ISSUE TITLE
Cookiecutter sometimes doesn't work in an Ubuntu 12.04 VM with Vagrant

### ISSUE THREAD

**Issue by audreyfeldroy** [cookiecutter/cookiecutter#107]
@pydanny had trouble getting Cookiecutter to work in an Ubuntu 12.04 VM with Vagrant. Here's the error he got. 

```
vagrant@precise64:~/tmp$ cookiecutter https://github.com/pydanny/cookiecutter-django.git
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.7.0', 'console_scripts', 'cookiecutter')()
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter-0.7.0-py2.7.egg/cookiecutter/main.py", line 115, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter-0.7.0-py2.7.egg/cookiecutter/main.py", line 47, in cookiecutter
    clone_to_dir=config_dict['cookiecutters_dir']
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter-0.7.0-py2.7.egg/cookiecutter/vcs.py", line 80, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "/usr/lib/python2.7/subprocess.py", line 506, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I tried to replicate this myself in my own Ubuntu 12.04 VM with Vagrant, but:
- it worked fine for me. Could not replicate.
- I also ran the test suite there and all tests passed.

Would love it if anyone had insight on this. I'm also having trouble with this one because my knowledge of subprocess is limited.

**Comment by ad-m** [comment]
```
adas@adas-AMILO-Pro-V3205:~/Devel$ git --version
git version 1.9.1
adas@adas-AMILO-Pro-V3205:~/Devel$ cookiecutter https://github.com/ad-m/cookiecutter-django/
You've cloned /home/adas/.cookiecutters before. Is it okay to delete and re-clone it? [Y/n] y
Traceback (most recent call last):
  File "/home/adas/.local/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.9.1', 'console_scripts', 'cookiecutter')()
  File "/home/adas/.local/lib/python2.7/site-packages/cookiecutter/main.py", line 169, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/home/adas/.local/lib/python2.7/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    no_input=no_input
  File "/home/adas/.local/lib/python2.7/site-packages/cookiecutter/vcs.py", line 92, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/home/adas/.cookiecutters/'
```
