### ISSUE TITLE
cookiecutter fails to load dictioanary default value from cookiecutterrc

### ISSUE THREAD

**Issue by ssbarnea** [cookiecutter/cookiecutter#1232]
### Description:
Using an entire dictionary variable expansion with cookiecutter seems to not be possible. The expected behavior was to see the entire nested dictionary loaded as jinja can easily use it for expansions.
```
---
default_context:
    company: ""
    platforms:
        - name: Fedora
          versions: [all]
        - name: CentOS
          versions: ["8"]
cookiecutters_dir: "~/.cookiecutters/"
```

### What I've run:

```
Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cookiecutter/config.py", line 113, in get_user_config
    env_config_file = os.environ['COOKIECUTTER_CONFIG']
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'COOKIECUTTER_CONFIG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/bin/molecule", line 11, in <module>
    load_entry_point('molecule', 'console_scripts', 'molecule')()
  File "/Users/ssbarnea/os/click/click/core.py", line 828, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ssbarnea/os/click/click/core.py", line 781, in main
    rv = self.invoke(ctx)
  File "/Users/ssbarnea/os/click/click/core.py", line 1227, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ssbarnea/os/click/click/core.py", line 1227, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ssbarnea/os/click/click/core.py", line 1046, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ssbarnea/os/click/click/core.py", line 590, in invoke
    return callback(*args, **kwargs)
  File "/Users/ssbarnea/os/click/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ssbarnea/os/molecule/molecule/command/init/role.py", line 166, in role
    r.execute()
  File "/Users/ssbarnea/os/molecule/molecule/command/init/role.py", line 80, in execute
    self._process_templates(template_directory, self._command_args, role_directory)
  File "/Users/ssbarnea/os/molecule/molecule/command/init/base.py", line 62, in _process_templates
    no_input=False,
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cookiecutter/main.py", line 54, in cookiecutter
    default_config=default_config,
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cookiecutter/config.py", line 118, in get_user_config
    return get_config(USER_CONFIG_PATH)
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/cookiecutter/config.py", line 69, in get_config
    yaml_dict = poyo.parse_string(file_handle.read())
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/parser.py", line 280, in parse_string
    return parser()
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/parser.py", line 273, in __call__
    match = self.find_match()
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/parser.py", line 254, in find_match
    node = callback(match)
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/parser.py", line 67, in _wrapper
    result = wrapped_function(parser, match, **kwargs)
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/parser.py", line 168, in parse_simple
    return Simple(variable, level, value, parent=parent)
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/_nodes.py", line 78, in __init__
    super(Simple, self).__init__(**kwargs)
  File "/Users/ssbarnea/.pyenv/versions/3.6.8/lib/python3.6/site-packages/poyo/_nodes.py", line 47, in __init__
    raise ValueError("Parent of ChildMixin instance needs to be a Container.")
ValueError: Parent of ChildMixin instance needs to be a Container.
FAIL: 1
```

**Comment by Ejjaffe** [comment]
Hello from March 2023!

When installing `cookiecutter` via conda, using the default `anaconda` channel installs version `1.7.3` which still uses `poyo` to parse `.cookiecutterrc`, and throws this exact error. So, if you're still seeing this error message in 2023 you may want to try installing from `-c conda-forge`, which currently has version `2.1.1`, and throws an entirely different yaml validation error :)
