### ISSUE TITLE
Non-rendered variable in the project-template name causes error

### ISSUE THREAD

**Issue by skarnl** [cookiecutter/cookiecutter#1430]
* Cookiecutter version: 1.7.2
* Python version: 3.7.5
* Operating System: OSX (10.14.6)

### Description:

When using a non-rendered variable (starting with an underscore) for the directory-name, cookiecutter gives an error.

### What I've run:

_cookiecutter.json_
```
{
    "game_name": "",
    "_game_slug": "{{ cookiecutter.game_name.lower().replace(' ', '-') }}",
    "game_slug": "{{ cookiecutter.game_name.lower().replace(' ', '-') }}",
}
```

When I set the template-folder-name to `{{cookiecutter.game_slug}}` (so I use the variable without the underscore) it will create the right directory:

_terminal output_
```
❯ cookiecutter boilerplate-project
game_name []: this is a test with CAPTIALS and spaces
game_slug [this-is-a-test-with-captials-and-spaces]:
```
👍

But when I replace use the non-rendered variable (`_game_slug`) in the template-folder-name, it gives an error. The reason why I want the variable to be non-rendered, is because I want to base the variable-value on the game_name. And I don't want an user to be able to overwrite this slug.

I get the following error:

```
❯ cookiecutter ../godot--boilerplate
game_name []: this is a test with spaces and CAPITALS
game_slug [this-is-a-test-with-spaces-and-capitals]:

Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/site-packages/cookiecutter/generate.py", line 161, in generate_file
    shutil.copyfile(infile, outfile)
  File "/usr/local/Cellar/cookiecutter/1.7.2/libexec/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: "/Users/oskar/projects/gamedev/godot/test/{{ cookiecutter.game_name.lower().replace(' ', '-') }}/screens/.DS_Store"
```

And I have 2 folders where half of the files are in one and half are in the other:

![image](https://user-images.githubusercontent.com/3471506/86126424-9b589000-bade-11ea-9ae5-3e70cc4b4ec6.png)

**Comment by Perdiga** [comment]
same issue here

**Comment by mwilson8** [comment]
same issue here, the above comment doesn't seem to help unfortunately

**Comment by samj1912** [comment]
Did you use the above to set a default in your pre gen hook?

**Comment by mwilson8** [comment]
What's temporarily working for me 
```commandline
pip install git+git://github.com/cookiecutter/cookiecutter.git@623e4b9f03b36bcd0c69acc52046cc4d98baac41
```

**Comment by edesz** [comment]
Hi @skarnl, as @samj1912 [commented](), this can be done with a pre gen hook. The `game_slug` variable should be taken out of `cookiecutter.json` and it should be set using the hook.

Below is a demonstration of how to do this for your use case

`cookiecutter.json`
```
{
    "game_name": ""
}
```

The pre gen hook is `hooks/pre_gen_project.py` and it contains the following to update your `cookiecutter` context
```python
import sys

"""{{ cookiecutter.update(
    {
        "game_slug": cookiecutter.game_name.lower().replace(' ', '-'),
    }
)}}"""

sys.exit(0)

```

This means there will not be a prompt for `game_slug` when you run `cookiecutter ...` to generate your template. However, the updated variable `game_slug` will be accessible.

`{{cookiecutter.database}}/{{cookiecutter.game_slug}}/mytest.txt`
```
The input was "{{cookiecutter.game_name}}".

The slug is "{{cookiecutter.game_slug}}".
```

When this is run using
```bash
$ cookiecutter .....
```
it produces a file `test/this-is-a-test-with-captials-and-spaces/mytest.txt` with the correctly rendered contents
```
The input was "this is a test with CAPTIALS and spaces".

The slug is "this-is-a-test-with-captials-and-spaces".
```

This is a convenient method to specify a value for `game_slug` that cannot be overwritten by the user.

This seems to be a viable solution for your intended use-case.

**Comment by njiles** [comment]
@edesz This example still fails for me (cookiecutter version 1.7.2):

```
$ cookiecutter -v test
DEBUG cookiecutter.config: User config not found. Loading default config.
DEBUG cookiecutter.main: context_file is test/cookiecutter.json
DEBUG cookiecutter.generate: Context generated is OrderedDict([('cookiecutter', OrderedDict([('game_name', '')]))])
game_name []: this is a test with CAPTIALS and spaces
DEBUG cookiecutter.utils: Making sure path exists: /Users/nicholasiles/.cookiecutter_replay/
DEBUG cookiecutter.find: Searching test for the project template.
DEBUG cookiecutter.find: The project template appears to be test/{{cookiecutter.game_slug}}
DEBUG cookiecutter.generate: Generating project from test/{{cookiecutter.game_slug}}...
Unable to create project directory '{{cookiecutter.game_slug}}'
Error message: 'collections.OrderedDict object' has no attribute 'game_slug'
Context: {
    "cookiecutter": {
        "_template": "test",
        "game_name": "this is a test with CAPTIALS and spaces"
    }
}
```

However, if I rename the `{{cookiecutter.game_slug}}` directory to `{{cookiecutter.game_name}}` then everything runs ok, and `this is a test with CAPTIALS and spaces/mytest.txt` is generated and contains the correctly rendered contents that you describe. This plus the output posted above makes me think that maybe the project template is being generated first (before `cookiecutter.game_slug` has been created), and then `pre_gen_project.py` is being run afterwards?

**Comment by simobasso** [comment]
Hey @njiles, could you check if https://github.com/cookiecutter/cookiecutter/pull/1339 solve your problem?

@mwilson8 suggest it in https://github.com/cookiecutter/cookiecutter/issues/1430#issuecomment-765511653

is merged but never releases

**Comment by samj1912** [comment]
Variables with a single underscore are not rendered. You would need to either set it manually in a pre gen hook using a context update or use double underscores. https://github.com/cookiecutter/cookiecutter/pull/1339#issuecomment-613680626

**Comment by njiles** [comment]
@simobasso @samj1912 Thanks for the responses - my comment was to remark that @edesz 's example doesn't work, for me at least, rather than to request help for an issue that I was having.

However, for completeness, the version at 623e4b9 still fails with the same error:
```
$ cookiecutter --version
Cookiecutter 2.0.0 from /Users/nicholasiles/anaconda3/envs/cc-gh/lib/python3.9/site-packages (Python 3.9)

$ cookiecutter -v test
DEBUG cookiecutter.config: User config not found. Loading default config.
DEBUG cookiecutter.main: context_file is test/cookiecutter.json
DEBUG cookiecutter.generate: Context generated is OrderedDict([('cookiecutter', OrderedDict([('game_name', '')]))])
game_name []: this is a test with CAPTIALS and spaces
DEBUG cookiecutter.utils: Making sure path exists: /Users/nicholasiles/.cookiecutter_replay/
DEBUG cookiecutter.find: Searching test for the project template.
DEBUG cookiecutter.find: The project template appears to be test/{{cookiecutter.game_slug}}
DEBUG cookiecutter.generate: Generating project from test/{{cookiecutter.game_slug}}...
Unable to create project directory '{{cookiecutter.game_slug}}'
Error message: 'collections.OrderedDict object' has no attribute 'game_slug'
Context: {
    "cookiecutter": {
        "_template": "test",
        "game_name": "this is a test with CAPTIALS and spaces"
    }
}
```
so I still think that maybe the project template is being generated first (before cookiecutter.game_slug has been created), and then pre_gen_project.py is being run afterwards?
