### ISSUE TITLE
Recurive Cookiecutters ? Moar Cookies !

### ISSUE THREAD

**Issue by OvalAdmin** [cookiecutter/cookiecutter#1434]
* Cookiecutter version: 1.6.0
* Template project url: https://git.manaikan.com/opensource/biscuits.git
* Python version: 3.6/7?
* Operating System: Windoze

### Description:

I am trying to leverage the fact that Cookiecutter is smart enough to checkout different branches against the `post_gen_hook`.
Ideally this would work as follows :

1) Fire up Cookiecutter against the master branch of ones cookiecutter
2) Provide a choice in the branches' cookiecutter.json that allows the user to select another branch
3) Process the cookiecutter as per usual 
4) Within the `post_gen_hook`  invoke cookiecutter against another branch of the same repository that the user selected in step 2; repeat from step 2 (and it is cookies all the way down.)

By carefully creating the branches such that not two paths overlap it ought to be possible to build up a project where one can selectively pick and choose the components they are interested in; with a little parsing it might be possible to do more then this (I'm thinking leo like file generation here but haven't tried).

From my first attempt it seems that pulling down the second branch is clobbering the download of the first branch both. That is both branches are downloaded into cookiecutter/Biscuits.

### What I've run:

```
E:\Python>cookiecutter https://git.manaikan.com/opensource/biscuits.git --output-dir E:\temp\pytest
You've downloaded C:\Users\USER\.cookiecutters\biscuits before. Is it okay to delete and re-download it? [yes]: y
company []:
project [Project]:
product [project]:
package [project]:
summary [Project Summary]:
website []:
author []:
editor []:
email []:
Select program:
1 -
2 - python
3 - go
Choose from 1, 2, 3 (1, 2, 3) [1]: 2
release [0.0.0]:
version [0.0]:
copyyear [2020]:
Select license:
1 - Apache License 2.0
2 - Boost Software License
3 - BSD Zero Clause License
4 - BSD 2 Clause 'Simplified' License
5 - BSD 3 Clause 'Clear' License
6 - BSD 3 Clause 'New' or 'Revised' License
7 - BSD 4 Clause 'Original' License
8 - Do What The F*ck You Want To Public License v2
9 - GNU Affero General Public License 3.0
10 - GNU General Public License 3.0
11 - GNU Lesser General Public License 3.0
12 - LaTeX Project Public License v1.3c
13 - Open Software License 3.0
14 - MIT License
15 - Mozilla Public License 2.0
16 - Unlicense
Choose from 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16) [1]:
['__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__']
You've downloaded C:\Users\USER\.cookiecutters\biscuits before. Is it okay to delete and re-download it? [yes]:
Traceback (most recent call last):
  File "c:\python\64bit\362\lib\shutil.py", line 391, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\.cookiecutters\\biscuits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Temp\tmp0iyqbbq9.py", line 43, in <module>
    overwrite_if_exists=True)              # We are clobering the directory we just created and need to be able to override what is there
  File "c:\python\64bit\362\lib\site-packages\cookiecutter\main.py", line 63, in cookiecutter
    password=password
  File "c:\python\64bit\362\lib\site-packages\cookiecutter\repository.py", line 103, in determine_repo_dir
    no_input=no_input,
  File "c:\python\64bit\362\lib\site-packages\cookiecutter\vcs.py", line 90, in clone
    clone = prompt_and_delete(repo_dir, no_input=no_input)
  File "c:\python\64bit\362\lib\site-packages\cookiecutter\utils.py", line 111, in prompt_and_delete
    rmtree(path)
  File "c:\python\64bit\362\lib\site-packages\cookiecutter\utils.py", line 42, in rmtree
    shutil.rmtree(path, onerror=force_delete)
  File "c:\python\64bit\362\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\python\64bit\362\lib\shutil.py", line 393, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\python\64bit\362\lib\site-packages\cookiecutter\utils.py", line 32, in force_delete
    func(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\USER\\.cookiecutters\\biscuits'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

### What I'd like

I'm hoping there is some hidden flag I can leverage to either control where the cookie cutter resides e.g. having hierarchically named branches and having the cookies downloaded to hierarchically organized folders under cookiecutter/biscuits would be first prize. 

Otherwise it seems I have two options :

 * Override the config file and replacing `cookiecutter_dir` 
 * Switch to cookie cutter folders instead (Perhaps this was their original intention ?).

**Comment by OvalAdmin** [comment]
There is a shiny 1.7.2 on PyPI. I switched to that and tried the directory trick on a new branch, `master-directories`. Upon this branch I managed to get the recursive calls working, switching from folder to folder rather then from branch to branch. 

I'll use this route and mark the topic as closed. Thanks for an excellent package :D
