### ISSUE TITLE
Empty directories correctly named with double under variable, but files are placed in separate, incorrectly named directory (should be named by double under variable)

### ISSUE THREAD

**Issue by ianscottknight** [cookiecutter/cookiecutter#1461]
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/ianscottknight/cookiecutter-data-science-poetry-template/tree/0.1.1
* Python version: 3.8.5
* Operating System: macOS Catalina 10.15.6

### Description:

I've got a basic poetry project cookiecutter template, that I've defined to take some basic variables like project_name, author_name, etc., and set up a poetry project with my pre-defined data science project structure. I was running a test using a dummy name "project_name", which should produce the cookiecutter.__repo_name variable as "project-name". Running cookiecutter correctly creates the repo "project-name" and populates it with all the correct directories, such that the directories all match up with my designated project structure. However, all the directories are empty, and the actual files are placed in a separately created directory called, literally, "{{ cookiecutter.project_name|lower|replace(' ', '-')|replace('_', '-') }}", which is placed in my home directory, adjacent to "project-name". So, it seems that there is some problem with filepaths for files that does not exist for the filepaths of directories. 

### What I've run:

cookiecutter https://github.com/ianscottknight/cookiecutter-data-science-poetry-template.git --checkout 0.1.1

```
project_name [project_name]: 
version [0.1.0]: 
description []: 
author_name [Ian Scott Knight]: 
author_email [isk@alumni.stanford.edu]: 
Select license:
1 - MIT
2 - BSD-3
3 - GNU GPL v3.0
4 - Apache Software License 2.0
Choose from 1, 2, 3, 4 [1]: 
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "/usr/local/lib/python3.8/site-packages/cookiecutter/generate.py", line 179, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
FileNotFoundError: [Errno 2] No such file or directory: "/Users/ianscottknight/{{ cookiecutter.project_name|lower|replace(' ', '-')|replace('_', '-') }}/project_name/__init__.py"
```
![image](https://user-images.githubusercontent.com/25094252/95035990-6cbcf900-067b-11eb-8667-9fef5614ed72.png)

**Comment by ianscottknight** [comment]
Seems related to https://github.com/cookiecutter/cookiecutter/issues/1430#issue-648135364

**Comment by edesz** [comment]
Hi @ianscottknight, it looks like the problem is caused by the use of double underscore (private variables) in the `.json` file and `cookiecutter-data-science-poetry-template/{{ cookiecutter.__repo_name }}/`.

[Private variables](https://cookiecutter.readthedocs.io/en/latest/advanced/private_variables.html#private-variables) are supported for `cookiecutter==2.0.0` while the version on PyPi ([1.7.2](https://pypi.org/project/cookiecutter/)) [doesn't support private variables](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/index.html). See more discussion here [#1115 (comment)](https://github.com/cookiecutter/cookiecutter/issues/1115#issuecomment-747915096).

You could temporarily remove the double underscore (which will then require user input for `repo_name`) in `cookiecutter.json` and from `cookiecutter-data-science-poetry-template/{{ cookiecutter.__repo_name }}/
` as a workaround until the new version is available. With these changes, the template (branch 0.1.1) seems to render fine for me.

**Comment by mwilson8** [comment]
Currently working for me (author of #1430) install the version from that commit
```commandline
pip install git+git://github.com/cookiecutter/cookiecutter.git@623e4b9f03b36bcd0c69acc52046cc4d98baac41
```

**Comment by connerxyz** [comment]
Why isn't the version (2.0?) with this version released yet? Thank.s

**Comment by xadamxk** [comment]
I'm using CookieCutter v2.1.1 and am facing this issue.
The proposed fixes above are not working along with this thread: https://github.com/cookiecutter/cookiecutter/issues/1430#issuecomment-765634948

Anyone have a fix?
