### ISSUE TITLE
Sometimes the cookiecutter replay fail with the same files/packages/*

### ISSUE THREAD

**Issue by LozanoMatheus** [cookiecutter/cookiecutter#1487]
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/LozanoMatheus/cookiecutter-helm
* Python version: Python 3.6
* Operating System: CentOS Linux release 7.9.2009 / 4.19.121-linuxkit - Docker image of centos 7

### Description:

I have a cookiecutter that generates the Helm template files. Sometimes, it works and sometimes it doesn't. I don't change anything, just run the Docker again (the cookiecutter is running in Docker). Same files, same *. 

I just added the `--verbose`, I'll post the result once it fails again.

### What I've run:

```bash
cookiecutter \
    --replay \
    --overwrite-if-exists \
    --output-dir "/tmp/" \
    --checkout "${Cookiecutter_Version}" \
    git@github.com:Lozanomatheus/cookiecutter-helm.git
```

### Error output:

```text
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/cli.py", line 152, in main
    skip_if_file_exists=skip_if_file_exists,
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/main.py", line 80, in cookiecutter
    context = load(config_dict['replay_dir'], template_name)
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/replay.py", line 53, in load
    context = json.load(infile)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by LozanoMatheus** [comment]
Oh, there is not that much data with `--verbose` for this case.

```text
DEBUG cookiecutter.config: User config not found. Loading default config.
DEBUG cookiecutter.utils: Making sure path exists: /root/.cookiecutters/
DEBUG cookiecutter.utils: Created directory at: /root/.cookiecutters/
DEBUG cookiecutter.vcs: repo_dir is /root/.cookiecutters/helm-template
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/cli.py", line 152, in main
    skip_if_file_exists=skip_if_file_exists,
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/main.py", line 80, in cookiecutter
    context = load(config_dict['replay_dir'], template_name)
  File "/usr/local/lib/python3.6/site-packages/cookiecutter/replay.py", line 53, in load
    context = json.load(infile)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by simobasso** [comment]
Hey @LozanoMatheus :wave:
Sorry about the late response. Can I help you in some way, or you resolved?

**Comment by LozanoMatheus** [comment]
Hi @simobasso 
No, unfortunately, I couldn't find why it's failing. I tried to use the files locally and from git, both fail. Also, I used Docker to try with the files locally, so the files always were the same (and sometimes it works, sometimes doesn't work)

**Comment by simobasso** [comment]
@LozanoMatheus 👋 , could you please try to use the master of this repo instead of the pip version of cookiecutter?
