### ISSUE TITLE
Add git to the installation instructions

### ISSUE THREAD

**Issue by haesleinhuepf** [cookiecutter/cookiecutter#1527]
* Cookiecutter version: 2.8.1
* Template project url: https://github.com/napari/cookiecutter-napari-plugin
* Python version: 3.8.5
* Operating System: Windows 10

### Description:
Hi all, 

I'm getting an error "cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed." when running cookiecutter. Obviously, I don't have git installed in my command line. As you are mentioning what to do in case pip is not installed in [cookiecutters installation instructions](https://cookiecutter.readthedocs.io/en/1.7.2/installation.html#install-cookiecutter), would you mind putting a comment on how to install git? On Windows in particular, `conda install git` is much easier compared to what google suggests as discussed [in a related issue](https://github.com/napari/cookiecutter-napari-plugin/issues/22).

Of course, it would be even more awesome if cookiecutter could during installation check if git is installed :-)

Best,
Robert

### What I've run:

```
pip install cookiecutter
cookiecutter https://github.com/napari/cookiecutter-napari-plugin
```

```
Traceback (most recent call last):
  File "c:\users\rober\miniconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\rober\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rober\miniconda3\Scripts\cookiecutter.exe\__main__.py", line 7, in <module>
  File "c:\users\rober\miniconda3\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\rober\miniconda3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\rober\miniconda3\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\rober\miniconda3\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\rober\miniconda3\lib\site-packages\cookiecutter\cli.py", line 140, in main
    cookiecutter(
  File "c:\users\rober\miniconda3\lib\site-packages\cookiecutter\main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "c:\users\rober\miniconda3\lib\site-packages\cookiecutter\repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "c:\users\rober\miniconda3\lib\site-packages\cookiecutter\vcs.py", line 84, in clone
    raise VCSNotInstalled(msg)
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.
```

**Comment by simobasso** [comment]
Hey @haesleinhuepf, thanks for reaching out!

> I'm getting an error "cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed." when running cookiecutter. Obviously, I don't have git installed in my command line. As you are mentioning what to do in case pip is not installed in cookiecutters installation instructions, would you mind putting a comment on how to install git? On Windows in particular, conda install git is much easier compared to what google suggests as discussed in a related issue.

I'm not sure about adding a specific guide on how to install a tool that is not a strict requirement of cookiecutter. You can use cookiecutter without `git` (with `hg` for example) and can be redundant to add (and maintain 😅 ) a guide for all the platforms that we should support when you can easily find it using google.

> Of course, it would be even more awesome if cookiecutter could during installation check if git is installed :-)

if you check https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/vcs.py#L75 cookiecutter raises that error because it checks if git is installed or not :-)

I'm going to close this one but feel free to reopen it if needed.

Thanks!
