### ISSUE TITLE
Add function to Jinja environment for camelCasing?

### ISSUE THREAD

**Issue by connerxyz** [cookiecutter/cookiecutter#1596]
* Cookiecutter version: 1.7.2
* Template project url: N/A
* Python version: ^3.6
* Operating System: macOS, linux, windows

### Description:

I need our template to map a variety of user input into camelCase in order to match certain organizational naming conventions. I have found this difficult since I can't seem to use list comprehensions using `{{ }}` syntax in the `cookiecutter.json` file.

**It would be easy to define a function that does what I want, but how do I then add my function to the jinja environment to call within `cookiecutter.json`?**

### What I've run:

```
# cookiecutter.json
{
    ...,
    "sub_org": "My Team",
    "code_base_name": "Code Base Name",
    "package_name": "{{ cookiecutter.code_base_name.lower().replace('-', ' ').replace(' ', '_') }}",
    "github_repo_name": "{{ cookiecutter.sub_org.replace(' ', '').lower() }}-{{ cookiecutter.parent_project_name.split()[0].lower() + ''.join(cookiecutter.parent_project_name.split()[1:]) }}_{{ cookiecutter.code_base_name.split()[0].lower() + ''.join([x.capitalize() for x in cookiecutter.code_base_name.split()[1:]]) }}",
    ...
}
```

Results in 

```
Traceback (most recent call last):
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/cookiecutter/main.py", line 93, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/cookiecutter/prompt.py", line 202, in prompt_for_config
    val = render_variable(env, raw, cookiecutter_dict)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/cookiecutter/prompt.py", line 158, in render_variable
    template = env.from_string(raw)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/U6020643/git/labs-standards_python-basePackageTemplate/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 'for'
```

**Comment by connerxyz** [comment]
I've got many people using my template and I definitely don't like having to add another prerequisite dependency... but it does work. Thanks.

**Comment by icj217** [comment]
I had a similar need in jinja and found the following worked well enough for my use case where the delimiter was consistent:
```
{{ name.split('-')|map('capitalize')|join }}
```
