### ISSUE TITLE
Creation failed: cookiecutter.exceptions.FailedHookException: Hook script failed 

### ISSUE THREAD

**Issue by enryH** [cookiecutter/cookiecutter#1616]
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/MolSSI/cookiecutter-cms
* Python version: 3.8.8
* Operating System: Windows 10

### Description:

Running cookiecutter throws `FailedHookException`

### What I've run:

```
>>> cookiecutter("https://github.com/MolSSI/cookiecutter-cms.git")
You've downloaded C:\Users\Henry\.cookiecutters\cookiecutter-cms before. Is it okay to delete and re-download it? [yes]:
project_name [ProjectName]: tetest
repo_name [tetest]:
first_module_name [tetest]:
author_name [Your name (or your organization/company/team)]: enryh
author_email [Your email (or your organization/company/team)]: henry@cpr.ku.dk
description [A short description of the project (less than one line).]: jep top
Select open_source_license:
1 - MIT
2 - BSD-3-Clause
3 - LGPLv3
4 - Not Open Source
Choose from 1, 2, 3, 4 [1]:
Select dependency_source:
1 - Prefer conda-forge over the default anaconda channel with pip fallback
2 - Prefer default anaconda channel with pip fallback
3 - Dependencies from pip only (no conda)
Choose from 1, 2, 3 [1]: 2
Select include_ReadTheDocs:
1 - y
2 - n
Choose from 1, 2 [1]: 1
The system cannot find the path specified.
Stopping generation because pre_gen_project hook script didn't exit successfully
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Henry\anaconda3\lib\site-packages\cookiecutter\main.py", line 101, in cookiecutter
    result = generate_files(
  File "C:\Users\Henry\anaconda3\lib\site-packages\cookiecutter\generate.py", line 293, in generate_files
    _run_hook_from_repo_dir(
  File "C:\Users\Henry\anaconda3\lib\site-packages\cookiecutter\generate.py", line 237, in _run_hook_from_repo_dir
    run_hook(hook_name, project_dir, context)
  File "C:\Users\Henry\anaconda3\lib\site-packages\cookiecutter\hooks.py", line 131, in run_hook
    run_script_with_context(script, project_dir, context)
  File "C:\Users\Henry\anaconda3\lib\site-packages\cookiecutter\hooks.py", line 115, in run_script_with_context
    run_script(temp.name, cwd)
  File "C:\Users\Henry\anaconda3\lib\site-packages\cookiecutter\hooks.py", line 86, in run_script
    raise FailedHookException(
cookiecutter.exceptions.FailedHookException: Hook script failed (exit status: 1)
```

I also tried the commandline version, but this did not provide the detailed traceback.

**Comment by enryH** [comment]
So the error is raised in the created script.

```
"""
Pre Cookie Generation script(s)

If any error is raised, the cookie cutter creation fails and crashes
"""

import re
import sys

MODULE_REGEX = r'^[_a-zA-Z][_a-zA-Z0-9]+$'
EMAIL_REGEX = r'[^@]+@[^@]+\.[^@]+'

repo_name = 'test'
module_name = 'test'

author_email = 'enryh@cpr.ku.dk'

for key in [repo_name, module_name]:
    if not re.match(MODULE_REGEX, key):
        print(key, re.match(MODULE_REGEX, key))
        print('ERROR: "{}" is not a valid Python module name!'.format(key))

        # exits with status 1 to indicate failure
        sys.exit(1)

if not re.match(EMAIL_REGEX, author_email):
    print('ERROR: "{}" is not a valid email address!'.format(author_email))

    # exits with status 1 to indicate failure
    sys.exit(1)
```

which itself does seem to work, but not through calling in  a subprocess.... I will investigate this further as it seems to be that I have to restrictive execution rights set up...

**Comment by enryH** [comment]
Out of curiosity: Is there any specific reason why these checks are performed in a temporary script?

**Comment by adammlarge** [comment]
I have a very similar pre_gen_project hook (regex match) and getting the same error message. Not sure if there is a solution, but I'd love to find out!
