### ISSUE TITLE
python setup.py build failed about cookiecutter@2.0.1 on centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [cookiecutter/cookiecutter#1622]
* Cookiecutter version:2.0.1
* Template project url:
* Python version:3.8.8
* Operating System:centos8_aarch64

### Description:
```console
[root@localhost spack-src]# pip install setuptools-scm
Looking in indexes: http://mirrors.tools.huawei.com/pypi/simple/
Collecting setuptools-scm
  Downloading http://mirrors.tools.huawei.com/pypi/packages/bc/bf/353180314d0e27929703faf240c244f25ae765e01f595a010cafb209ab51/setuptools_scm-6.3.2-py3-none-any.whl (33 kB)
Requirement already satisfied: tomli>=1.0.0 in /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/site-packages (from setuptools-scm) (1.2.2)
Requirement already satisfied: packaging>=20.0 in /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/site-packages (from setuptools-scm) (21.3)
Requirement already satisfied: setuptools in /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/py-setuptools-50.3.2-a454d3mwnji6fkymf5sk2rrns7j76dq2/lib/python3.8/site-packages (from setuptools-scm) (50.3.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/site-packages (from packaging>=20.0->setuptools-scm) (3.0.6)
Installing collected packages: setuptools-scm
Successfully installed setuptools-scm-6.3.2
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
[root@localhost spack-src]# python setup.py build
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    setuptools.setup(
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/py-setuptools-50.3.2-a454d3mwnji6fkymf5sk2rrns7j76dq2/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/py-setuptools-50.3.2-a454d3mwnji6fkymf5sk2rrns7j76dq2/lib/python3.8/site-packages/setuptools/dist.py", line 423, in __init__
    _Distribution.__init__(self, {
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/py-setuptools-50.3.2-a454d3mwnji6fkymf5sk2rrns7j76dq2/lib/python3.8/site-packages/setuptools/dist.py", line 695, in finalize_options
    ep(self)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/py-setuptools-50.3.2-a454d3mwnji6fkymf5sk2rrns7j76dq2/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/site-packages/setuptools_scm/integration.py", line 65, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 177, in _get_version
    parsed_version = _do_parse(config)
  File "/home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.8.8-m3k3pvne56yo7wyd7a3bwf7mugupszik/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 135, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/home/spack-stage/root/spack-stage-py-cookiecutter-2.0.1-pyq3dbxvwc2yoanujkwzoudrpl5s2u67/spack-src'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```
I want to know why a compilation error is reported when setuptools-scm has been installed.

**Comment by insspb** [comment]
Not related to project, related to usage in spack-stage
