### ISSUE TITLE
Github ssh clone repo failing

### ISSUE THREAD

**Issue by LongBeachHXC** [cookiecutter/cookiecutter#1644]
* Cookiecutter version: 2.0.2
* Template project url: Private
* Python version: 3.9.1
* Operating System: WSL

### Description:

According to this [github docs page](https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories) ssh remote urls look like the following:

`git@github.com:user/repo.git`

However, when using cookiecutter, the program is attempting to use the following remote url which is causing the request to fail

`ssh://git@github.com:user/repo.git`

### What I've run:

I've included the following in my local fork and all works as expected.

Problem is, I read the [git-scm docs](https://git-scm.com/docs/git-clone#_git_urls) and it appears that the remote syntax is valid. This seems to be github specific?

```
repo_url = repo_url.split('//')[1]
```

**Comment by LongBeachHXC** [comment]
if you change the colon (`:`) to a `/` it works.

```
cookiecutter git+ssh://git@github.com/user/repo.git
```

**Comment by giuseppeambrosio97** [comment]
With bitbucket it seems is not working

`cookiecutter git+ssh://git@bitbucket.org:<myorg>/repo.git --verbose`

stack trace:
DEBUG cookiecutter.config: User config not found. Loading default config.
DEBUG cookiecutter.utils: Making sure path exists (creates tree if not exist): /home/giambrosio/.cookiecutters
DEBUG cookiecutter.vcs: repo_dir is /home/giambrosio/.cookiecutters/isp_templates
ERROR cookiecutter.vcs: git clone failed with error: Cloning into 'isp_templates'...
ssh: Could not resolve hostname bitbucket.com:<myorg>: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Traceback (most recent call last):
  File "/home/giambrosio/.pyenv/versions/3.9.12/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/home/giambrosio/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/giambrosio/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/giambrosio/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/giambrosio/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/giambrosio/.pyenv/versions/3.9.12/lib/python3.9/site-packages/cookiecutter/cli.py", line 202, in main
    cookiecutter(
  File "/home/giambrosio/.pyenv/versions/3.9.12/lib/python3.9/site-packages/cookiecutter/main.py", line 80, in cookiecutter
    base_repo_dir, cleanup_base_repo_dir = determine_repo_dir(
  File "/home/giambrosio/.pyenv/versions/3.9.12/lib/python3.9/site-packages/cookiecutter/repository.py", line 107, in determine_repo_dir
    cloned_repo = clone(
  File "/home/giambrosio/.pyenv/versions/3.9.12/lib/python3.9/site-packages/cookiecutter/vcs.py", line 103, in clone
    subprocess.check_output(  # nosec
  File "/home/giambrosio/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/giambrosio/.pyenv/versions/3.9.12/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'ssh://git@bitbucket.org:<myorg>/repo.git']' returned non-zero exit status 128.

but of course If I git clone the repo with ssh it works!
