### ISSUE TITLE
`git clone` subprocess fails for SSH when key requires passphrase

### ISSUE THREAD

**Issue by jeffmccormick** [cookiecutter/cookiecutter#1653]
* Cookiecutter version: 1.7.3
* Template project url: git+ssh://git@github.com/audreyr/cookiecutter-pypackage.git
* Python version: 3.10
* Operating System: Windows/Ubuntu

### Description:

When trying to run cookiecutter on a git URI that uses an SSH key that is protected by passphrase, the `git clone` subprocess fails and throws. The CLI does not prompt the user for the passphrase and instead just fails out. Full traceback below.

```sh
Traceback (most recent call last):
  File "/home/user/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/home/user/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "/home/user/.local/lib/python3.8/site-packages/cookiecutter/repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "/home/user/.local/lib/python3.8/site-packages/cookiecutter/vcs.py", line 101, in clone
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'ssh://git@github.com/audreyr/cookiecutter-pypackage.git']' returned non-zero exit status 128.
```

### What I've run:

Tested and received same failure in both Windows and Ubuntu 20.04. Using a SSH key _without_ a passphrase works just fine in both environments.

### Expected Behavior:

If the clone operation requires an SSH passphrase, the prompt is passed through to the user while executing the clone.

### Proposed Solution:

Replace [`subprocess.check_output()` call](https://github.com/cookiecutter/cookiecutter/blob/2.0.2/cookiecutter/vcs.py#L95) with `subprocess.run()` which will not fail out early during the authentication challenge. Process success can be checked manually and output can still be captured.

**Comment by jakeberesford-palmetto** [comment]
I'm running into this issue on mac os, with no passphrase set on my SSH key. Seems like `git+ssh://git@github.com` isn't working.

**Comment by D3mianGianoz** [comment]
@ericof I have the same issue
