### ISSUE TITLE
git clone subprocess failed for private github repo when username and password required

### ISSUE THREAD

**Issue by pikhovkin** [cookiecutter/cookiecutter#1654]
* Cookiecutter version: 1.7.3
* Template project url: private repo
* Python version: 3.8.12
* Operating System: Ubuntu

### Description:

git clone subprocess failed for private github repo when username and password required

### What I've run:

`cookiecutter https://github.com/.../cookiecutter-django`
or
`cookiecutter gh:.../cookiecutter-django`

```bash
Username for 'https://github.com': pikhovkin
Password for 'https://pikhovkin@github.com': ******************************

Traceback (most recent call last):
  File "/.../.envs/cookiecutter/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/cookiecutter/main.py", line 67, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/cookiecutter/repository.py", line 110, in determine_repo_dir
    cloned_repo = clone(
  File "/.../.envs/cookiecutter/lib/python3.8/site-packages/cookiecutter/vcs.py", line 101, in clone
    subprocess.check_output(
  File "/home/.../.pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/.../.pyenv/versions/3.8.12/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/.../cookiecutter-django']' returned non-zero exit status 128.
```
If I run `cookiecutter /path_to_template/cookiecutter-django` locally everything is fine.

Maybe this issue and #1653 are related.

**Comment by jeffmccormick** [comment]
My hunch is that this indeed related to #1653. When I get some time, I'll put together a PR to fix both.
