### ISSUE TITLE
Generation breaks with config-file

### ISSUE THREAD

**Issue by jensens** [cookiecutter/cookiecutter#1734]
* Cookiecutter version: current master of today at 449f8771650a3daab7c8163b015576eae26150b8 (I dont know since when it is broken)

### Description:

If a config file is given it breaks with 

```
Traceback (most recent call last):
  File "/app/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/app/lib/python3.9/site-packages/click/core.py", line 1130, in call
    return self.main(args, kwargs)
  File "/app/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/app/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, ctx.params)
  File "/app/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(args, kwargs)
  File "/app/lib/python3.9/site-packages/cookiecutter/cli.py", line 202, in main
    cookiecutter(
  File "/app/lib/python3.9/site-packages/cookiecutter/main.py", line 69, in cookiecutter
    config_dict = get_user_config(
  File "/app/lib/python3.9/site-packages/cookiecutter/config.py", line 104, in get_user_config
    return get_config(config_file)
  File "/app/lib/python3.9/site-packages/cookiecutter/config.py", line 69, in get_config
    config_dict = merge_configs(DEFAULT_CONFIG, yaml_dict)
  File "/app/lib/python3.9/site-packages/cookiecutter/config.py", line 44, in merge_configs
    for k, v in overwrite.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

### What I've run:

`cookiecutter -f --no-input --config-file instance.yml https://github.com/bluedynamics/cookiecutter-zope-instance`

with file

```YAML
default_context:
    wsgi_http_listen: localhost:8080
    initial_user_name: admin
    initial_user_password: verysecretidonttellyou
    load_zcml:
        package_includes: ['my.addon']
    db_storage: direct
```

**Comment by iham** [comment]
was a typo - when instance.yml is created and make is done an EMPTY instance.yaml is created - which can't have items as the empty yaml doesn't have any entries.
