### ISSUE TITLE
Cookiecutter fails to repalce template string in filename for underscore variable

### ISSUE THREAD

**Issue by con-f-use** [cookiecutter/cookiecutter#1831]
* Cookiecutter version: 2.1.0
* Python version: 3.10.10
* Operating System: NixOS 22.11 (linux)

### Description:

```
Traceback (most recent call last):
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/cookiecutter/cli.py", line 194, in main
    cookiecutter(
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/cookiecutter/main.py", line 114, in cookiecutter
    result = generate_files(
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/cookiecutter/generate.py", line 373, in generate_files
    generate_file(
  File "/home/confus/devel/pypackage/.direnv/python-3.10.10/lib/python3.10/site-packages/cookiecutter/generate.py", line 194, in generate_file
    with open(outfile, 'w', encoding='utf-8', newline=newline) as fh:
FileNotFoundError: [Errno 2] No such file or directory: "/home/confus/devel/pypackage/{{ cookiecutter.package_name.lower() | replace(' ', '_') | replace('-', '_') | replace('.', '_') | trim() }}/.python-ci/README.rst"
```

### What I've run:

```
cookiecutter ./   # in my template directory
```

With this directory structure and files in the template directory (minimal example that reproduces the error for me):

```terminal
$ tree
.
├── cookiecutter.json
└── {{cookiecutter._package_slug}}
    └── .python-ci
        └── README.rst
$ cat cookiecutter.json
{
    "package_name": "qa-package",
    "_package_slug": "{{ cookiecutter.package_name.lower() | replace(' ', '_') | replace('-', '_') | replace('.', '_') | trim() }}"
}
```

`README.rst` is empty, but its content doesn't matter.

**Comment by con-f-use** [comment]
Ah nevermind, it's [double underscores for rendered private variables](https://github.com/cookiecutter/cookiecutter/pull/1339).
