### ISSUE TITLE
Does nested templates need to be a remote Git repository?

### ISSUE THREAD

**Issue by Jarmos-san** [cookiecutter/cookiecutter#1926]
* Cookiecutter version: `Cookiecutter 2.3.0`
* Template project url: https://github.com/Weburz/cookiecutter-templates
* Python version: `Python 3.11.5`
* Operating System: `Ubuntu 20.10`

### Description:

We decided to organise all our templates under [a single repository](https://github.com/Weburz/cookiecutter-templates) for easier maintenance. And we did so while following the instructions as written in the documentations here - [Nested Configuration Files](https://cookiecutter.readthedocs.io/en/stable/advanced/nested_config_files.html#). When we run the `cookiecutter gh:Weburz/cookiecutter-templates`, we do get prompted to choose a template which we do but then it crashes. We believe the crash is because `cookiecutter` attempts to "_clone_" the nested template directory (i.e `simple-project`). But the nested `simple-project` directory is obviously not a remote `git` repository hence it crashes.

Here are the contents of the top-level `cookiecutter.json` file:

```json
{
  "template": ["Simple Project (./simple-project)"]
}
```

and the `simple-project` nested template directory looks somewhat like this:

```console
.
└── simple-project/
    ├── {{cookiecutter.project_slug}}/
    │   ├── .github/
    │   │   └── dependabot.yml
    │   ├── workflows/
    │   │   └── qa-checks.yml
    │   ├── .editorconfig
    │   ├── .gitattributes
    │   ├── .gitignore
    │   └── README.md
    └── cookiecutter.json
```

On the other hand `cookiecutter` seems to properly generate the project structure if we specify the directory to get the templates from with this command:

```console
cookiecutter gh:Weburz/cookiecutter-templates --directory "simple-project"
```

So, did we make some mistakes while creating the template files? Or is it something else?

### What I've run:

```console
$ cookiecutter gh:Weburz/cookiecutter-templates
  [1/1] Select template
    1 - Simple Project (./simple-project)
    Choose from [1] (1):
ERROR: git clone failed with error: Cloning into 'simple-project'...
fatal: remote error:
 Weburz/cookiecutter-templates/./simple-project is not a valid repository name
Visit https://support.github.com/ for help

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/cookiecutter/cli.py", line 202, in main
    cookiecutter(
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/cookiecutter/main.py", line 140, in cookiecutter
    return cookiecutter(
           ^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/cookiecutter/main.py", line 75, in cookiecutter
    repo_dir, cleanup = determine_repo_dir(
                        ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/cookiecutter/repository.py", line 107, in determine_repo_dir
    cloned_repo = clone(
                  ^^^^^^
  File "/home/linuxbrew/.linuxbrew/Cellar/cookiecutter/2.3.0/libexec/lib/python3.11/site-packages/cookiecutter/vcs.py", line 103, in clone
    subprocess.check_output(  # nosec
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/Weburz/cookiecutter-templates/./simple-project.git']' returned non-zero exit status 128.```

**Comment by ericof** [comment]
It was fixed on version 2.3.1
