### ISSUE TITLE
Formatting files that contain double curly braces

### ISSUE THREAD

**Issue by dhorkel** [cookiecutter/cookiecutter#1927]
* Cookiecutter version: 2.3.0
* Template project url:
* Python version: 3.7.9
* Operating System: Windows 10

### Description:

I'm trying to use cookiecutter for Azure DevOps pipeline yaml files. Unfortunately Azure pipelines use double curly braces for evaluated conditional statements. For example:

```
variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    buildDesignation: 'alpha'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    buildDesignation: 'beta'
```

When I try to template these files jinja throws an error (see below).

### What I've run:

So far I've tried:

1. Rewriting my pipelines. This works in some cases but I can't avoid `{{ }}` for some kinds of conditionals.
2. An attempted hacky solution of adding private variables in cookiecutter.json for each of the conditionals. Eg.
`__dev_condition":"{{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}` then adding `{{ cookiecutter.dev_condition}}`.
This seems to result in the same error (see below). I'm guessing because files are run through jinja multiple times?

I've currently added the pipeline files to `_copy_without_render` but would appreciate any help towards a real solution so I could use cookiecutter variables within the pipeline.

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\cookiecutter\__main__.py", line 6, in <module>
    main(prog_name="cookiecutter")
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\cookiecutter\cli.py", line 216, in main
    keep_project_on_failure=keep_project_on_failure,
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\cookiecutter\main.py", line 178, in cookiecutter
    keep_project_on_failure=keep_project_on_failure,
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\cookiecutter\generate.py", line 409, in generate_files
    project_dir, infile, context, env, skip_if_file_exists
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\cookiecutter\generate.py", line 189, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\dhorkel\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File ".ci\build_pipeline.yaml", line 12, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'eq'
  File ".ci\build_pipeline.yaml", line 12
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
```

**Comment by dhorkel** [comment]
Thank you @Bandgren!! Guess I should have googled harder.
