### ISSUE TITLE
Cookiecutter throws `jinja2.exceptions.TemplateNotFound` error when underlying template project also contains Jinja references

### ISSUE THREAD

**Issue by chrimaho** [cookiecutter/cookiecutter#1946]
* Cookiecutter version: `2.3.1`
* Template project url: private
* Python version: `3.10.6`
* Operating System: Ubuntu

### Description:

In my projects, I am using [`mkdocs`][mkdocs] as the website renderer for my Python package docs. The specific theme that I am using within MkDocs is called [`mkdocs-material`][mkdocs-material]. Within MkDocs-Material, there is a process to provide template overrides (see [Customization][customization] page for more details).

These override templates could look like this (from [this source][source1]):

```html
{% extends "base.html" %}

{% block htmltitle %}
  <title>Lorem ipsum dolor sit amet</title>
{% endblock %}
```

Or perhaps like this (from [this source][source2]):

```html
{% extends "base.html" %}

{% block outdated %}
  You're not viewing the latest version.
  <a href="{{ '../' ~ base_url }}"> 
    <strong>Click here to go to latest.</strong>
  </a>
{% endblock %}
```

Infact, there's a whole bunch of templates available from MkDocs-Material, see more info [here][all-templates].

What's important to note here is that these templates _also_ use Jinja2 syntax for their structure.

And so, what happens here is that when I call `cookiecutter` on my template project, and when my template project contains files which also have Jinja2 references, then I get an error from Cookiecutter:

```txt
DEBUG cookiecutter.generate: Check docs/overrides/main.html to see if it's a binary
Traceback (most recent call last):
  File "/home/MYNAME/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/home/MYNAME/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/chmahone/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/MYNAME/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/MYNAME/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/MYNAME/.local/lib/python3.10/site-packages/cookiecutter/cli.py", line 202, in main
    cookiecutter(
  File "/home/MYNAME/.local/lib/python3.10/site-packages/cookiecutter/main.py", line 175, in cookiecutter
    result = generate_files(
  File "/home/MYNAME/.local/lib/python3.10/site-packages/cookiecutter/generate.py", line 408, in generate_files
    generate_file(
  File "/home/MYNAME/.local/lib/python3.10/site-packages/cookiecutter/generate.py", line 195, in generate_file
    rendered_file = tmpl.render(**context)
  File "/home/MYNAME/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/MYNAME/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "docs/overrides/main.html", line 1, in top-level template code
  File "/home/MYNAME/.local/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
```

You'll notice here that Cookiecutter calls Jinja to replace it's own template values; which is expected behaviour. However, when the files within the template project _also_ contain Jinja templates, then Cookiecutter _also_ tries to render those templats as well; which is not expected behaviour.

[mkdocs]: https://www.mkdocs.org/
[mkdocs-material]: https://squidfunk.github.io/mkdocs-material/
[customization]: https://squidfunk.github.io/mkdocs-material/customization/
[source1]: https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks
[source2]: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning
[all-templates]: https://github.com/squidfunk/mkdocs-material/tree/master/src/templates

### Issue:

Please help me to resolve this issue, so I can use my template files, without Cookiecutter throwing an error when it cannot find the underlying template files.

Thank you.

**Comment by CalledSidd** [comment]
I'm facing the same issue, I'm using Django and on my templates I'm having the same error
```
    raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: base.html
```
and because of this error the whole project is not getting loaded, I also got similar errors when using ` {% csrf_token %}` 
any fixes for this other than not using templates at all?

**Comment by UNREALre** [comment]
You have to exclude this templates from being rendered by cookiecutter. Use _copy_without_render param inside cookiecutter.json file like this:
`
  "_copy_without_render": [
    "*.html",
    "*.js",
    "*.map",
    "*.css",
    "*.yaml",
    "*.tpl"
  ]
`
List all your files that you need just to copy without rendering and everything will be fine!
