### ISSUE TITLE
Feature-Request: Use inheritance with nested configuration

### ISSUE THREAD

**Issue by donnyyung** [cookiecutter/cookiecutter#2028]
* Cookiecutter version: 2.6.0
* Template project url:
* Python version: 3.11
* Operating System: Macos

### Description:

I'm trying to use nested [configuration files ](https://cookiecutter.readthedocs.io/en/stable/advanced/nested_config_files.html#) since we have one repo with a multiple templates for users to create an app whether it's python or go or some other language.  Some of the files like our README, our circle pipelines, etc. will be the same templates for all the services, so I was also trying to use [inheritance](https://cookiecutter.readthedocs.io/en/stable/advanced/templates.html) to have a set of shared files at the top of the repo that I can use in both templates, the file structure looks like: 

main-directory/
    ├── project-1
    │   ├── cookiecutter.json
    │   ├── {{cookiecutter.project_slug}}
    |       │   ├── ...
    ├── package
    │   ├── cookiecutter.json
    │   ├── {{cookiecutter.project_slug}}
    |       │   ├── ...
    ├── cookiecutter.json
    ├── templates/
     └── README_tpl.md
    
 And then I have a file in project-1/cookiecutter.project_slug/README.md that contains: 
 ```
 {% include "README_tpl.md" %}
 ```   
### What I've run:
And when I try to create an app using cookiecutter from the root dir, I get this error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/cookiecutter/cli.py", line 203, in main
    cookiecutter(
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/cookiecutter/main.py", line 143, in cookiecutter
    return cookiecutter(
           ^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/cookiecutter/main.py", line 182, in cookiecutter
    result = generate_files(
             ^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/cookiecutter/generate.py", line 409, in generate_files
    generate_file(
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/cookiecutter/generate.py", line 209, in generate_file
    rendered_file = tmpl.render(**context)
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "README.md", line 1, in top-level template code
  File "/usr/local/Cellar/cookiecutter/2.6.0/libexec/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: README_tpl.md
```

Admittedly I haven't looked at the code for cookiecutter (apologies!), so I'm not sure if this is a bug or just something not supported, I suspect the latter. So wanted to confirm that and also ask if this is something you might want to support in the future or if it's something that can't be supported for xyz reason.  

Thank you!

**Comment by jessebrizzi** [comment]
I am currently attempting something similar and it looks to be not currently supported. 

[The issue is the jinja2 FileSystemLoader is hardcoding the location for the inheritance folder to `../templates` .](https://github.com/cookiecutter/cookiecutter/blob/da0df9d3a09205749307c403f06a1b4ca3af4cb8/cookiecutter/generate.py#L347)

A possible solution could be adding support to pass in the location of the inheritance folder as a optional argument to the `cookiecutter()` call. Or some symlink setup with your multiple template directories to get it working with the current version.

**Comment by butterlyn** [comment]
Has anyone found a workaround for this (while we're waiting on the pull request to be approved)?

**Comment by jessebrizzi** [comment]
If you are using the Cookiecutter CLI I don't have anything to suggest.

I'm calling into cookiecutter from within another project of mine so I have been messing around with this ugly monkey patch in the meantime to try and unblock myself.

```python
from cookiecutter.main import cookiecutter
from jinja2 import FileSystemLoader

# Setup FileSystemLoader Monkey Patch
original_init = FileSystemLoader.__init__

def patched_init(
    self: FileSystemLoader,
    searchpath: str | os.PathLike | Sequence[str | os.PathLike],
    encoding: str = "utf-8",
    followlinks: bool = False,
) -> None:
    if (
        isinstance(searchpath, Sequence)
        and not isinstance(searchpath, str)
        and searchpath == ["..", "../templates"]
    ):
        searchpath = [*searchpath, "custom/templates"]
    original_init(self, searchpath, encoding, followlinks)

FileSystemLoader.__init__ = patched_init

try:
    cookiecutter(
        template="example_template_uri",
        ...
    )
finally:
    # Restore the original FileSystemLoader.__init__ method
    FileSystemLoader.__init__ = original_init

```

**Comment by jamesmyatt** [comment]
We're using the pre-prompt hooks to copy common files into each of the nested templates (provided they don't already exist). It's not ideal and can be slow, but it works well.
