### ISSUE TITLE
Issue when using _(?x)_ as part of a regular expression in Creating files command. 

### ISSUE THREAD

**Issue by edgarefraindp** [cookiecutter/cookiecutter#2076]
* Cookiecutter version: 2.6.0 (2024-02-21)
* Template project url: https://github.com/microsoft/python-sklearn-classifier-cookiecutter/
* Python version: 3.11
* Operating System: Windows 11 Pro 23H2

### Description:
Following the steps of the quickstart guide: ([Quickstart: Create a project from a Cookiecutter template](https://learn.microsoft.com/en-us/visualstudio/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter?view=vs-2022)). In step 4, after cloning and pressing the "Add to solution" button, an error occurs when creating the template files.

I have identified that this issue is in: [https://github.com/cookiecutter/cookiecutter/blob/main/cookiecutter/repository.py](https://github.com/cookiecutter/cookiecutter/issues/url)

To fix it in my local environment, I have made the following, 
I changed this:
```
REPO_REGEX = re.compile(
    r"""
# something like git:// ssh:// file:// etc.
((((git|hg)\+)?(git|ssh|file|https?):(//)?)
 |                                                          # or
 (\w+@[\w\.]+)                                    # something like user@...
)
""",
    re.VERBOSE,
)
```

to this:
```
REPO_REGEX = re.compile(r"""(?x)             # Verbose mode.
    ((((git|hg)\+)?(git|ssh|https?):(//)?)   # Something like git:// ssh:// etc.
    |                                        # or
    (\w+@[\w\.]+)                            # something like user@...
)""")
```

Justification: The issue seems to be that the flag _(?x)_ is placed within the string of the regular expression instead of outside of it. The _(?x)_ flag should be placed **outside of the string of the regular expression to indicate that the verbose mode will be used**, allowing comments and white spaces within the regular expression to make it more readable.

I've gone ahead and submitted Pull Request #2075. Hopefully, I've adhered to the standard correctly.

### What I've run:

```
<details><summary>Output from General in VisualStudio22</summary>
<p>
----- Creating files using template 'microsoft/python-sklearn-classifier-cookiecutter' -----
Traceback (most recent call last):
  File "c:\program files\microsoft visual studio\2022\enterprise\common7\ide\extensions\microsoft\cookiecutter\cookiecutter_run.py", line 22, in <module>
    from cookiecutter.main import cookiecutter
  File "C:\Users\XXXX\AppData\Local\Microsoft\CookiecutterTools\env\Lib\site-packages\cookiecutter\main.py", line 33, in <module>
    REPO_REGEX = re.compile(r"""
                 ^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 989, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 464, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python311\Lib\re\_parser.py", line 850, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 1 (line 2, column 1)
C:\Users\XXXX\AppData\Local\Microsoft\CookiecutterTools\env\scripts\python.exe returned an exit code of 1.
----- Failed to create files using template 'microsoft/python-sklearn-classifier-cookiecutter' -----

</p>
</details> 

```

**Comment by edgarefraindp** [comment]
Update... I changed 
This: 
```
REPO_REGEX = re.compile(r"""(?x)             # Verbose mode.
    ((((git|hg)\+)?(git|ssh|https?):(//)?)   # Something like git:// ssh:// etc.
    |                                        # or
    (\w+@[\w\.]+)                            # something like user@...
)""")
```
to this: 
```
REPO_REGEX = re.compile(r"""(?x)                # Verbose mode
    (
        ((git|hg)\+)?(git|ssh|https?|file)    # Protocols
        ://
    )
    |                                         # or
    (\w+@[\w\.]+)                             # user@hostname
""")
```

To improvements wit CICD test... sry...

Justification:
The issue is that the _(?x)_ verbose mode flag was not placed correctly at the start of the regular expression in REPO_REGEX. This caused a compilation error. The flag needs to be at the start to enable verbose mode properly.

This is in:  #2077 (Update repository.py / Fix placement of verbose mode flag in REPO_REGEX)
