### ISSUE TITLE
misspelled github shortcut crashes

### ISSUE THREAD

**Issue by yarko** [cookiecutter/cookiecutter#348]
trying [github shortcuts](http://cookiecutter.readthedocs.org/en/latest/usage.html#works-directly-with-git-and-hg-mercurial-repos-too) with a typo produced a traceback.   For example,

```
$ cookiecutter gh:audreyr/cookiecutter-pypackage.git
$ # or:
$ cookiecutter gh:aureyr/cookiecutter-pypackage
```

generates this:

```
$ cookiecutter gh:aureyr/cookiecutter-pypackage.git
Cloning into 'cookiecutter-pypackage.git'...
Username for 'https://github.com': yarko
Password for 'https://yarko@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/aureyr/cookiecutter-pypackage.git.git/' not found
Traceback (most recent call last):
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.8.0', 'console_scripts', 'cookiecutter')()
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/lib/python2.7/site-packages/cookiecutter/main.py", line 169, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/lib/python2.7/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    no_input=no_input
  File "/Users/yak007/workspace/cookiecutter/env/cookiecutter/lib/python2.7/site-packages/cookiecutter/vcs.py", line 108, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'git', u'clone', u'https://github.com/autreyr/cookiecutter-pypackage.git.git']' returned non-zero exit status 128
```

... which seems a bit much just for a simple typo.

I played around with a first-draft fix, which no doubt people would do differently - but it illustrates the issue. PR #349

**Comment by theodesp** [comment]
Maybe a more sensible approach is to check if the repo exists before cloning so we can extract a better error handling scenario?

**Comment by theodesp** [comment]
I'm willing to work on this if its ok
