### ISSUE TITLE
pkg_resources.DistributionNotFound Error

### ISSUE THREAD

**Issue by abelnation** [cookiecutter/cookiecutter#793]
- Cookiecutter version: `1.4.0`
- Template project url:
- Python version: `Python 2.7.12 :: Continuum Analytics, Inc.`
- Operating System: Mac OSX 10.11
### Description:

New anaconda install.  Installed to `/usr/local/anaconda2`.  Error when executing:

```
~$ cookiecutter https://github.com/jupyter/widget-cookiecutter.git
```

Error:

```
~$ cookiecutter https://github.com/jupyter/widget-cookiecutter.git
Traceback (most recent call last):
  File "/usr/local/anaconda2/bin/cookiecutter", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2927, in <module>
  File "/usr/local/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "/usr/local/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "/usr/local/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 635, in _build_master
  File "/usr/local/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 943, in require
  File "/usr/local/anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg/pkg_resources/__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'cookiecutter==1.4.0' distribution was not found and is required by the application
```

Also:

```
ipython                   5.0.0                    py27_0
conda                     4.1.11                   py27_0
```

**Comment by luzfcb** [comment]
@abelnation what is the output of:

```
conda list --export
```
and

```
pip freeze
```

put the output on https://gist.github.com/ and then send the link

**Comment by hackebrot** [comment]
Hey @abelnation, can you provide above info. Maybe @luzfcb can help. 😃

**Comment by WesleyTheGeolien** [comment]
Hi, I just hit this problem again, cookie cutter was installed using `conda install -c conda-forge cookiecutter`, I am on Linux 64 bit system. However uninstalling and reinstalling using pip worked for me.

**Comment by insspb** [comment]
Outdated
